import "./globals.css";

import type { Metadata } from "next";

import { SiteNavigationMenu } from "@/components/navigation-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-end p-4">
          <SiteNavigationMenu />
        </header>
        {children}
      </body>
    </html>
  );
}
