import "./globals.css";

import type { Metadata } from "next";

import { SiteNavigationMenu } from "@/components/navigation-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <header className="fixed top-0 left-0 right-0 bg-white z-10 shadow-md">
          <div className="max-w-screen-xl mx-auto flex justify-end items-center p-4">
            <SiteNavigationMenu />
          </div>
        </header>
        <main className="flex-grow pt-16 overflow-y-auto flex justify-center">
          <div className="max-w-screen-xl w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
